spring:
  application:
     name: api-gateway

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION


server:
  port: 2020

zuul:
  routes:
    users-service:
      path: /v1/users/**
      stripPrefix: false
    rss-service:
      path: /v1/feeds/**
      stripPrefix: false
    auth-service:
      path: /v1/token
      stripPrefix: false
